USE [DBSISTEMAS]
GO

/****** Object:  View [dbo].[VW_ESTOQUE]    Script Date: 11/10/2023 21:42:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_ESTOQUE] AS 

SELECT P.ProDescricao, 
P.PROCODIGO,
SUM(EP.ENPQUANTIDADE) - (SELECT ISNULL(SUM(ITV.ITVQUANTIDADE),0) FROM ITENS_VENDA ITV WHERE ITV.ItvCodigoProduto = P.PROCODIGO) AS QUANTIDADE,


EP.EnpValorVenda AS VALORVENDA
FROM ENTRADA_PRODUTO EP
JOIN PRODUTO P ON P.ProCodigo = EP.EnpCodigoProduto 
GROUP BY P.ProDescricao, EP.EnpValorVenda,P.PROCODIGO
HAVING SUM(EP.ENPQUANTIDADE) - (SELECT ISNULL(SUM(ITV.ITVQUANTIDADE),0) FROM ITENS_VENDA ITV WHERE ITV.ItvCodigoProduto = P.PROCODIGO) > 0


GO


